name: super_linter
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - name: checkout_code
      uses: actions/checkout@v3

    - name: 'Lint code base'
      uses: github/super-linter/slim@v4
      env:
        VALIDATE8ALL8CODEBASE: true
        GITHUB_TOKEN: ${{secret.GITHUB_TOKEN}}