name: hadolint
on:
  push:
jobs: 
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
     -  name: run hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif

     -  name: upload analysis result to github-actions
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
