name: semgrep
on:
  push:
jobs: 
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    container:
      image: returntocorp/semgrep:1.74.0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4

      - name: upload sarif file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: result.sarif
          category: analysis-tool
        

      - name: "Execute semgrep"
        run: semgrep ci
        env:
          SEMGREP_RULES: p/default