name: semgrep
on:
  push:
jobs: 
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    container:
      image: returntocorp/semgrep:1.74.0
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4

      - name: "Execute semgrep"
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default


      - name: upload sarif file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
         