name: super_linter
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: checkout_code
      uses: actions/checkout@v5

    - name: 'Lint code base'
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}